global:
  valuesDirectoryURL: https://github.com/dagger-refuse-cool/edge-gitops/raw/main/
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

site:
  name: datacenter

  namespaces:
  - manuela-ci

  projects:
  - datacenter
 
  applications:
  - name: pipelines
    namespace: manuela-ci
    project: datacenter
    path: example
    plugin:
      name: helm-with-kustomize
